version: '3'
services:
  datadog:
    # image: datadog/agent:latest
    build: .
    ports:
      - "8125:8125/udp"
    environment:
      - DD_API_KEY=${DD_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro