kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.15.12
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1a"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1a"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1a"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1b"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1b"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1b"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1c"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1c"
- role: worker
  image: kindest/node:v1.15.12
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io=eu-central-1c"
