version: "3"

volumes:
  cassandra:

networks:
  cassandra:

services:
  cassandra-seed:
    image: cassandra
    container_name: cassandra-seed-node
    deploy:
      resources:
        limits:
          memory: 6Gb
    environment:
      - "JVM_OPTS=-Xms2048M -Xmx2048M"
    ports:
      - "7000:7000"
      - "7199:7199"
      - "9042:9042"
    networks:
      - "cassandra"
    volumes:
      - /tmp/cassandra/node0/data/:/var/lib/cassandra

  cassandra-node-1:
    image: cassandra
    deploy:
      resources:
        limits:
          memory: 6Gb
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "JVM_OPTS=-Xms2048M -Xmx2048M"
    networks:
      - "cassandra"
    volumes:
      - /tmp/cassandra/node1/data/:/var/lib/cassandra
    depends_on:
      - "cassandra-seed"

  cassandra-node-2:
    image: cassandra
    deploy:
      resources:
        limits:
          memory: 6Gb
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "JVM_OPTS=-Xms2048M -Xmx2048M"
    networks:
      - "cassandra"
    volumes:
      - /tmp/cassandra/node2/data/:/var/lib/cassandra
    depends_on:
      - "cassandra-node-1"

